version: '3'

services:
    market-api:
        depends_on:
            - db
        build: ./src/market-api
        image: market-api:latest
        ports:
            - 8080:8080
        restart: always
        
    market-frontend:
        depends_on:
            - market-api
        build: ./src/market
        image: diary:latest
        ports:
            - 80:80
        restart: always

    db:
        image: postgres:alpine
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

